name: Content Feedback
description: Provide feedback for exisiting vademecum content.
labels:
  - content
body:
- type: input
  id: url
  attributes:
    label: Vademecum URL
    description: What is the page you are referring to?
    placeholder: https://vademecum.mtrail.io/
- type: textarea
  attributes:
    label: Feedback
    description: What additions or corrections do you propose?
